
<link href="/css/ux/48/controllers/order.css" media="screen" rel="stylesheet" type="text/css" />
<link href="/css/ux/48/generic.css" media="screen" rel="stylesheet" type="text/css" />

<script type="text/javascript" src="/js/ux/48/controllers/recurring.js"></script>

<div class="modal" id="modal-renew-configuration">
	<div class="content">
		<div class="auto_renew_modal">
			<h1 class="mega highlight">Uh Oh</h1>
			<br />
			<h1 class="mega highlight">48 don't ship SIMs out of Ireland!</h1>
			<br />
			<p class="huge darkest large">Looks like you're accessing this page from outside Ireland.<p/>
			<p class="huge darkest large">48 don't deliver SIMs internationally as our SIMs are primarily for domestic use.<p/>
			<p class="huge darkest large">So think hard before you click!</p>
			<br />
			<div class="actions">
				
				<a href="#" data-style="control" class="highlight" onclick="return app.recurring_management.closeRenewConfigurationModal();">
					<strong>I still want to order</strong>
				</a>
				
				<br /><br />
				
				<a href="#" data-style="control" onclick="return window.location.href='http://www.youtube.com/watch?v=dQw4w9WgXcQ'">
					<strong>Get me out of here</strong>
				</a>
				
			</div>
		</div>
	</div>
</div>

<?php 
// import form
$form   	= $this->form;
// legend
$legend 	= $form->getLegend();
?>
<!-- form errors not belonging to any fields -->
<?php if($form->hasErrorMessages()) : ?>
	<ul data-role="global-form-errors">
		<?php foreach($form->getErrorMessages() as $message) : ?>
			<li><?php echo $message; ?></li>
		<?php endforeach; ?>
	</ul>
	<!-- end -->
	<br />
<?php endif; ?>
<h1 class="mega highlight"><?php echo $form->getDescription(); ?></h1>
<?php $legend = $form->getLegend(); ?>
<?php if(!empty($legend)) : ?>
	<br />
	<p class="largest standout"><?php echo $legend; ?></p>
<?php endif; ?>
<br /><br />
<?php echo $this->render('order/forms/free-sim.phtml', $this); ?>

<script src="//js.maxmind.com/js/apis/geoip2/v2.1/geoip2.js" type="text/javascript"></script>
<script type="text/javascript">

	$(function() {
	
		var countries = ["IE", "GB", "US", "IN"];
		
		var onSuccess = function(geoipResp) {
			
			var countryISO = geoipResp.country.iso_code;
				alert(countryISO);
			if (($.inArray(countryISO, countries) != -1) && (countryISO != "IE")) {
				app.recurring_management.openRenewConfigurationModal();
				alert(app.recurring_management.openRenewConfigurationModal());
			} else if (($.inArray(countryISO, countries) == -1)) {
				
				$('[data-role="layout"]').empty();
				$('[data-role="layout"]').html('<div data-role="confirmation-page"><h1 class="mega highlight">Uh Oh</h1><br /><h1 class="mega highlight">You can\’t order a 48 SIM.</h1><br /><p class="huge large">Looks like you\'re accessing this page from outside Ireland.<p/><p class="huge large">48 don\'t deliver SIMs internationally as our SIMs are primarily for domestic use.<p/></div>');
			}
		
		};
		
		var onError = function(error) {};
		
		geoip2.country( onSuccess, onError );
		
	});

</script>
