<div data-role="help-and-support-options">
	
	<h2 class="centered"><span>Help &amp; Support</span></h2>
	
	<p class="intro centered">
		Our customer care is all online. Why? Because it gives you quick and easy access to the help you need. No more bad hold music. We've 3 simple options, choose the one which works for you.
	</p>
	
	<ul class="help-and-support-options">
    	<li class="faq">
        	<h3><a href="/help#check-out-our-FAQs">Check out our FAQs &raquo;</a></h3>
            <span>There’s plenty we can do to help, but we find that most issues can be resolved by reading our FAQs.</span>
        </li>
	    <li class="community">
	        <h3><a href=" http://community.48months.ie">Ask the 48 Community &raquo;</a></h3>
	        <span>There are plenty of 48ers on the Community who are happy to help out. Simply post your query in the Need Help section for a speedy response.</span>
	    </li>
	    <li class="agent">
	        <h3><a href="/help/ask-agent">Contact Us &raquo;</a></h3>
	        <span>Got a question about your account? Ask a 48 Agent for help and they will get back to you within 24 hours.</span>
	    </li>
     </ul>
          
</div>