<? $this->headLink()->appendStylesheet('/css/ux2/matesrates.css'); ?>

<div data-role="main-portal-home-matesrates-options">

     <!--<h2 class="centered"><span>Mates Rates: <em id="matesrates-desc">Instant Credit</em></span></h2>-->
	 <h2 class="centered"><span class="matesratesimg"><img id="matesratesImg" src="/css/ux2/img/matesrates-2015/02_activatesim-MatesRates.png" /></span></h2>

     <div data-role="main-portal-home-matesrates" >

         <div id="main-portal-home-matesrates-icon" class="center">
        </div>

         <div id="main-portal-home-matesrates-text-header" class="center">
             <span>Recruit a friend. Get paid. Simple!</span>
         </div>

        <div id="main-portal-home-matesrates-text" class="center">
            <p class="intro centered">Get your mates signed up to 48 through Mates Rates and we’ll sort you out with up to €10 cash or credit. We won't forget your friends either. Win Win!</p>
        </div>

        <div id="main-portal-home-matesrates-button-container" class="center">
            <div class="alert-cell actions" style="display:inline-block">
                <a class="button bn-kick" href="/matesrates/what-is"><span><strong>Tell me more</strong></span></a>
            </div>
        </div>
     </div>
</div>
    
