CREATE TABLE USERS(ID INT PRIMARY KEY,USERNAME VARCHAR(25) NOT NULL, PASSWORD VARCHAR(25) NOT NULL, EMAIL VARCHAR(50) NOT NULL, BIRTHDATE VARCHAR(25) NOT NULL, PROFESSION VARCHAR(25) NOT NULL);

CREATE TABLE QUESTIONS(ID INT PRIMARY KEY,QUESTION VARCHAR(500) NOT NULL, OPTION1 VARCHAR(100), OPTION2 VARCHAR(100), OPTION3 VARCHAR(100), OPTION4 VARCHAR(100), ANSWER VARCHAR(100), SUBJECT VARCHAR(25));

CREATE TABLE SUBJECTS(ID INT PRIMARY KEY, SUBJECTNAME VARCHAR(25));

CREATE TABLE USERS_EXAM_QUESTIONS(ID INT PRIMARY KEY,FKUSERID INT NOT NULL, FKQUESTIONID INT NOT NULL,CONSTRAINT FK_USER_ADD FOREIGN KEY ("FKUSERID") REFERENCES USERS (ID), CONSTRAINT FK_QUESTION_ADD FOREIGN KEY ("FKQUESTIONID") REFERENCES QUESTIONS (ID), SELECTEDANSWER VARCHAR2(10) NOT NULL);



CREATE SEQUENCE  USERS_ID  MINVALUE 1 MAXVALUE 9999999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  CYCLE ;
CREATE SEQUENCE  QUESTIONS_ID  MINVALUE 1 MAXVALUE 9999999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  CYCLE ;
CREATE SEQUENCE  SUBJECTS_ID  MINVALUE 1 MAXVALUE 9999999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  CYCLE ;
CREATE SEQUENCE  USERS_EXAM_QUESTIONS_ID  MINVALUE 1 MAXVALUE 9999999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  CYCLE ;



INSERT INTO USERS(ID,USERNAME,PASSWORD,EMAIL,BIRTHDATE,PROFESSION) VALUES (USERS_ID.NEXTVAL,?,?,?,?,?)
INSERT INTO QUESTIONS(ID,QUESTION,OPTION1,OPTION2,OPTION3,OPTION4,ANSWER,SUBJECT) VALUES (QUESTIONS_ID.NEXTVAL,?,?,?,?,?,?,?)
INSERT INTO SUBJECTS(ID,SUBJECTNAME) VALUES (SUBJECTS_ID.NEXTVAL,?)
INSERT INTO USERS_EXAM_QUESTIONS(ID,FKUSERID,FKQUESTIONID,SELECTEDANSWER) VALUES (USERS_EXAM_QUESTIONS_ID.NEXTVAL,?,?,?)


DELETE FROM USERS WHERE ID = ?
DELETE FROM QUESTIONS WHERE ID = ?
DELETE FROM SUBJECTS WHERE ID = ?
DELETE FROM USERS_EXAM_QUESTIONS WHERE ID = ?


UPDATE USERS SET USERNAME = ?,PASSWORD = ?,EMAIL = ?,BIRTHDATE = ?,PROFESSION = ? WHERE ID = ?
UPDATE QUESTIONS SET QUESTION = ?,OPTION1 = ?,OPTION2 = ?,OPTION3 = ?,OPTION4 = ?,ANSWER = ?,SUBJECT = ? WHERE ID = ?
UPDATE SUBJECTS SET SUBJECTNAME = ? WHERE ID = ?
UPDATE USERS_EXAM_QUESTIONS SET FKQUESTIONID = ?,FKQUESTIONID = ?,SELECTEDANSWER = ? WHERE ID = ?