create table for Grow Aggriculture
===============================================


CREATE TABLE USERS (ID INT NOT NULL,NAME VARCHAR(25) NOT NULL, PASSWORD VARCHAR(45) NOT NULL, PRIMARY KEY(ID),USER_TYPE VARCHAR(50) NOT NULL,CREATED_DATE DATE NOT NULL,LAST_UPDATE DATE NOT NULL);

CREATE TABLE USER_DETAILS(ID REFERENCES USERS(ID),COMPANY VARCHAR2(45),USERNAME VARCHAR(50),EMAIL_ADDRESS VARCHAR2(50),FIRST_NAME VARCHAR2(50),LAST_NAME VARCHAR2(50),ADDRESS VARCHAR2(150),CITY VARCHAR2(50),COUNTRY VARCHAR2(50),POSTAL_CODE INT,ABOUT_ME VARCHAR2(500));

CREATE TABLE IMAGES (ID REFERENCES USERS(ID),USERS_PICTURE VARCHAR2(500),USERS_PICTURE_LOCATION VARCHAR2(900),FRUITS_VEGETABLES_NAME VARCHAR2(700),FRUITS_VEGETABLES_PIC_LOCATION VARCHAR2(900));



CREATE SEQUENCE  USERS_ID  MINVALUE 1 MAXVALUE 1000000 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  CYCLE ;

Trigger for LAST_UPDATE
======================================================
create or replace TRIGGER USERS_UP_INS
   BEFORE INSERT OR UPDATE
   ON USERS
   REFERENCING NEW AS new OLD AS old
   FOR EACH ROW
DECLARE
BEGIN
   :new.LAST_UPDATE   := SYSDATE;
EXCEPTION
   WHEN OTHERS
   THEN
      -- Consider logging the error and then re-raise
      RAISE;
END USERS_UP_INS;

